### PR TITLE
Support full list of GitHub keywords

### PR DESCRIPTION
**Pull request by mjcarroll**
Closes nikku/wuffle#71

### CODE REVIEW

**Comment by mjcarroll** [comment]
As an additional question here, should this support the keywords with a colon? For examples `Fixes: #71` vs `Fixes #71`.  It does not appear that it currently supports this capability.

**Comment by nikku** [comment]
> As an additional question here, should this support the keywords with a colon? For examples Fixes: #71 vs Fixes #71. It does not appear that it currently supports this capability.

What's your thought? I personally find it odd to use colons here but I see people doing it. So why not support / recognize that one, too.

**Comment by mjcarroll** [comment]
I think since Github supports it, it probably makes sense to support here as well.

**Comment by mjcarroll** [comment]
Added support for the colon.  Feedback welcome.  I originally attempted doing the `close|closes|closed` match with another group like `(close(s|d)?)` but it makes the match extraction logic break below, so simple seemed better.

If there are tests somewhere else that need to be updated, let me know, this seemed to be the right location.

**Pull request merged**
