### PR TITLE
Add issue linking to cards

### PR DESCRIPTION
**Pull request by joannenolan-sky**
Add issue linking to cards. Not just to closed issues
linked-issues

### CODE REVIEW

**Comment by nikku** [comment]
Thanks for your contribution!

We track displaying links in https://github.com/nikku/wuffle/issues/3 and support a whole set of links [under the hood](https://github.com/nikku/wuffle/blob/master/packages/app/lib/links.js#L1) already.

Does it make sense to implement all supported link types at once?

**Comment by joannenolan-sky** [comment]
That makes sense. I will add the other and update the PR

**Comment by joannenolan-sky** [comment]
We have updated this PR  with all the link types and it now shows all links for each type rather than just the first one.
We have also changed the card link to display the issue title instead of the respositoryName

**Comment by nikku** [comment]
A lot of work went into this PR and I'd like to better understand when you feel like it is ready to be merged.

Could you share an up-to-date screenshot with some rationale, why you ended up with that particular solution? Which links do you display, which links are implicit?

**Comment by joannenolan-sky** [comment]
This PR is to show all links not just closed linked issues show-links

We show all the links that are available in `links`. This allows us to see which issues have open PR's  and how issues are linked to each other via the parent/child relationship. 

We are plan to eventually show the icons for the relationships as well as per #3 . This is the first part of multiple PR's that we plan on raising. The second will be to add Epic linking and icons add-epic-icons and the third will be to add the dependency icons 
vizualise-dependencies
These changes are ready to be raised but they are all dependent on this issue being merged.

**Comment by nikku** [comment]
I'll have a look into this PR tonight.

:crossed_fingers:

**Comment by joannenolan-sky** [comment]
Brilliant, thanks.

**Comment by nikku** [comment]
I've squashed your changes and merged them via https://github.com/nikku/wuffle/commit/ae5e064e8aff309f91803d3b763aa28a45c743ba.

I was not exactly sure about these multiple link definitions for embedded links and ended up simplifying the whole logic via https://github.com/nikku/wuffle/commit/fd4a82cfb643db79d4d76a0e0ef465856e9ac160#diff-0e47c330cd1708169843adab601fbc95R37.

From what I understand that should not have broken any behavior.

It probably makes sense to implement link icons before releasing a new Wuffle version. Right now it, without the appropriate context, it is quite confusing to look at a highly linked issue landscape:

image

**Pull request closed without merging**
